# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aa3c2816b75ecf348ac1d6b6b6e35eb7d260aabd86eca3d103cc4c8bdc64ac80ee206060d0579d53f87d88e54e0de303545e6c74427ebe00033857296fc85db

test:
  secret_key_base: fb7227533b0b4fb3896eb956659217fa29ebbc2d8c9d38f50a47638f934662a88c2de6f3e5c6578df03eb8184034d5f990783e3eab20b639e9faf2fd445bef27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
